# Coolify Stack Configuration for Distill Webhook Visualizer
# Use this file to deploy as a Docker Compose stack in Coolify

version: '3.8'

services:
  app:
    image: distill-webhook-visualizer:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HOST: 0.0.0.0
      PORT: 8000
      DATABASE_URL: sqlite:///./data/monitoring.db
      LOG_LEVEL: info
      DOMAIN: "{{DOMAIN}}"
      SECRET_KEY: "{{SECRET_KEY}}"
      CORS_ORIGINS: "https://{{DOMAIN}}"
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    volumes:
      - app_data:/app/data
      - app_logs:/app/logs
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - traefik.enable=true
      - traefik.http.routers.distill.rule=Host(`{{DOMAIN}}`)
      - traefik.http.routers.distill.tls=true
      - traefik.http.routers.distill.tls.certresolver=letsencrypt
      - traefik.http.services.distill.loadbalancer.server.port=8000

volumes:
  app_data:
  app_logs: