version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=9988
      - DATABASE_URL=sqlite:///./data/monitoring.db
      - LOG_LEVEL=info
      - SECRET_KEY=distill-webhook-local-test-key
      - DOMAIN=localhost:9988
      - CORS_ORIGINS=http://localhost:9988
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "9988:9988"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9988/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  data:
  logs: